### ISSUE TITLE
Errortrace turns an unambiguous reference into an ambiguous one

### ISSUE THREAD

**Issue by lexi-lambda** [racket/errortrace#35]
Consider the following program:

```racket
#lang racket/base
(let ()
  (define-syntax-rule (m y)
    (begin
      (define x 'a)
      (define y 'b)
      (println x)))
  (m x)
  (println x))
```

This program compiles successfully without errortrace, but it fails with an ambiguous binding error when compiled with errortrace:

```
$ racket bug.rkt
'a
'b
$ racket -l errortrace -t bug.rkt
bug.rkt:7:15: x: identifier's binding is ambiguous
  in: x
  context...:
   #(1563 macro) #(1579 module) #(1582 module bug) #(1588 local)
   #(1589 intdef) #(1590 local) #(1591 intdef) #(1592 local)
   #(1593 intdef) #(1594 local) #(1595 intdef) [common scopes]
  matching binding...:
   local
   #(1563 macro) [common scopes]
  matching binding...:
   local
   #(1579 module) #(1582 module bug) #(1588 local) #(1589 intdef)
   #(1590 local) #(1591 intdef) #(1592 local) #(1593 intdef)
   #(1594 local) [common scopes]
  matching binding...:
   local
   #(1563 macro) #(1579 module) #(1582 module bug) #(1588 local)
   #(1589 intdef) #(1590 local) #(1591 intdef) #(1592 local)
   [common scopes]
  matching binding...:
   local
   [common scopes]
  common scopes...:
   #(1469 module) #(1472 module bug) #(1489 local) #(1490 intdef)
   #(1491 local) #(1492 intdef)
  errortrace...:
  location...:
   bug.rkt:7:15
```

Note that this does not happen if the definitions do not appear in an internal definition context: the program is accepted if the wrapping `let` is removed.

---

The error appears to be quite fundamental, to the point that I considered opening this issue on racket/racket instead of this repository. This program also triggers the bug:

```racket
#lang racket/base
(expand-syntax
 (expand-syntax
  #'(module m racket/base
      (let ()
        (define-syntax-rule (m y)
          (begin
            (define x 'a)
            (define y 'b)
            (println x)))
        (m x)
        (println x)))))
```

That is, `expand-syntax` is not idempotent.

**Comment by LeifAndersen** [comment]
Well...that was a fun bug to wake up to in the morning.

Question, was this behavior this way in the older (pre-set of scopes) expander?

**Comment by lexi-lambda** [comment]
No, I can confirm that both programs run successfully under Racket v6.2.1. To my surprise, however, they *also* run successfully on Racket v6.12, which is to say things worked correctly under the sets-of-scopes expander at one point in time (they just don’t work correctly under the Racket reimplementation of the sets-of-scopes expander). So perhaps this really is a racket/racket bug.

**Comment by lexi-lambda** [comment]
Alright, I’ve done a little more digging, and it looks like here is the difference. Both versions of the expander generate the following syntax:

```racket
(module m racket/base
  (#%module-begin
   (module configure-runtime '#%kernel
     (#%module-begin
      (#%require racket/runtime-config)
      (#%app configure '#f)))
   (#%app
    call-with-values
    (lambda ()
      (let-values ()
        (let-values (((x) 'a))
          (let-values (((x) 'b))
            (#%app println x)
            (#%app println x)))))
    print-values)))
```

The difference, naturally, is in the scopes. They are mostly identical, but under the 6.12 expander, the inner `x` identifier bound by `let-values` includes an additional use-site scope. In the current expander, the scopes on the inner `x` identifier are a strict subset of the scopes on the outer `x` identifier (the latter of which naturally has an extra macro-introduction scope).

I will confess that I don’t really understand why or even *how* Racket 6.12 includes this extra scope. Use site scopes are supposed to be pruned from identifiers that end up in binding position in a definition context. After all, if that were not the case, I would expect this program to be rejected:

```racket
(let ()
  (define-syntax-rule (m y)
    (begin
      (define y 'a)
      (println x)))
  (m x)
  (println x))
```

But somehow, it is not rejected, and under Racket 6.12, *both* uses of `x` end up with the use-site scope! Stepping through the expansion steps using the macro stepper under Racket 6.12 reveals a somewhat mystifying “Resolve variable (remove extra marks)” step that actually *replaces* the macro-introduction scope with a use-site scope (which is to say it is doing a bit more than “remove extra marks”!).

So my gut instinct is to say that Racket 6.12 was actually buggy. I don’t think that scope should be there, so I think what was probably actually happening was that the identifier kept around as the original binder in the expansion context was mistakenly the unpruned binder, even though the identifier used as the “key” had those scopes correctly pruned. Racket 7.0 fixed that bug, so it produces the correct result, but that bug conveniently made `expand-syntax` idempotent in this case.

**Comment by lexi-lambda** [comment]
I have just confirmed that, indeed, the Racket 6.12 behavior seems to have been an unintended bug. The old expander binds the identifiers with the use-site scopes removed, but it eventually [overwrites which binding identifiers their bindings are associated with](https://github.com/racket/racket/blob/4f9c2133041ae952ed34d5a208317ac86103158f/racket/src/racket/src/compile.c#L3757), and these identifiers happen to be the original, unpruned identifiers. This all seems to arise from the pressures inherent in writing the expander in C.

So I don’t think this is necessarily a racket/racket bug after all. The new behavior is intended. That said, I don’t have any idea how one would fix this particular issue without modifying the expander in some way.

**Comment by rmculpepper** [comment]
Here's another version of the issue that uses `local-expand` instead:

    #lang racket/base
    (require (for-syntax racket/base))

    (define-syntax (re-expand stx)
      (syntax-case stx ()
        [(_ e)
         (local-expand #'e 'expression null)]))

    (#%expression
     (re-expand
      (let ()
        (define-syntax-rule (m y)
          (begin
            (define x 'a)
            (define y 'b)
            (println x)))
        (m x)
        (println x))))

This program also signals an ambiguous binding error. The same error also occurs if the contents of the module are run at the top-level. That suggests the problem is unrelated to any special cases for modules or oddities of top-level expansion (ie, `expand` and `expand-syntax` vs `local-expand`).

**Comment by michaelballantyne** [comment]
Okay, so during the first expansion we get the scopes we'd expect...

(let ()
  (define x 'a)  ; module let macro
  (define y 'b)  ; module let
  (println x)    ; module let macro
  (println x))   ; module let

except that the expander turns the definition context into a letrec and
then into nested let-values (no new scopes here)

(let-values (((x) 'a))     ; module let macro
  (let-values (((x) 'b))   ; module let
    (#%app println x)      ; module let macro
    (#%app println x)))))  ; module let

Then re-expansion adds scopes for the let-values forms:

(let-values (((x) 'a))     ; module let macro let-values1
  (let-values (((x) 'b))   ; module let let-values1 let-values2
    (#%app println x)      ; module let macro let-values1 let-values2
    (#%app println x)))))  ; module let let-values1 let-values2

And there we get the ambiguity.

It is generally true of scope sets that if you expand and then reshuffle
identifiers so that the scope nesting is different vs the original
expansion you may get ambiguity. The translation to let-values is changing
the two `x`s from being in the same scope in the original program to
instead having the second `x` in a more nested scope, triggering the
problem.

If anyone could fill me in on the background, I don't understand the
rationale behind the definition-context to letrec to let-values translation
very well. Why is the transformation from letrec to plain let where
possible something that belongs in the expander?

**Comment by michaelballantyne** [comment]
Okay, so during the first expansion we get the scopes we'd expect...

```
(let ()
  (define x 'a)  ; module let macro
  (define x 'b)  ; module let
  (println x)    ; module let macro
  (println x))   ; module let
```

except that the expander turns the definition context into a letrec and
then into nested let-values (no new scopes here)

```
(let-values (((x) 'a))     ; module let macro
  (let-values (((x) 'b))   ; module let
    (#%app println x)      ; module let macro
    (#%app println x)))))  ; module let
```

Then re-expansion adds scopes for the let-values forms:

```
(let-values (((x) 'a))     ; module let macro let-values1
  (let-values (((x) 'b))   ; module let let-values1 let-values2
    (#%app println x)      ; module let macro let-values1 let-values2
    (#%app println x)))))  ; module let let-values1 let-values2
```

And there we get the ambiguity.

It is generally true of scope sets that if you expand and then reshuffle
identifiers so that the scope nesting is different vs the original
expansion you may get ambiguity. The translation to let-values is changing
the two `x`s from being in the same scope in the original program to
instead having the second `x` in a more nested scope, triggering the
problem.

If anyone could fill me in on the background, I don't understand the
rationale behind the definition-context to letrec to let-values translation
very well. Why is the transformation from letrec to plain let where
possible something that belongs in the expander?

**Comment by samth** [comment]
Unsurprisingly given @rmculpepper's example, this is also replicable in Typed Racket:

```
#lang typed/racket

(let ()
  (define-syntax-rule (m y)
    (begin
      (define x 'a)
      (define y 'b)
      (println x)))
  (m x)
  (println x))
```

**Comment by mflatt** [comment]
On the definition-context to letrec to let-values translation: The intent is that you can write

```
 (define x (some-complicated-function))
```

and not worry about whether the compiler will have to create a box to hold `x` due to the possibility that the called function uses `call/cc` — at least, as long as all your definitions in the same group avoid forward references. In other words, it's a way of picking a less expensive semantics for internal definitions versus traditional Scheme internal definitions (or just leaving things undefined as R6RS does). The conversion happens at the expander, because that's where internal definitions are implemented.

But the implementation of this conversion does appear to be wrong in the expander. I think the it needs to create a new scope at the same time that it creates a `let-values` layer. That extra scope is needed in expand-to-syntax mode, while expand-to-parsed mode doesn't need to do the extra work.

I'll investigate a repair. Thanks for the report and debugging so far!

**Comment by mflatt** [comment]
I've pushed a repair. It achieves its result through a slightly strange operation on the compile-time environment, but I think it works... I'll watch out for test failures as counter-examples.

**Comment by lexi-lambda** [comment]
Is there any reason to do the `letrec` to `let` conversion when not expanding in the `to-parsed?` mode? I guess that not doing it could be a backwards compatibility concern at this point, but it seems like leaving the `letrec` alone when expanding to syntax would be less delicate.

**Comment by samth** [comment]
The `letrec`-to-`let` conversion is definitely helpful for tools like TR, which then don't have to effectively do the same analysis in order to avoid more complex reasoning about `letrec`.

**Comment by lexi-lambda** [comment]
Yes, that makes sense, thanks!
